[theme]
primaryColor = "#2E86C1"
backgroundColor = "#F2F2F2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans-serif"

[theme.sidebar]
backgroundColor = "#2E86C1"
textColor = "#FFFFFF"
font = "sans-serif"

[theme.topBar]
backgroundColor = "#FFFFFF"
textColor = "#2E86C1"
font = "sans-serif"

[theme.button]
backgroundColor = "#2E86C1"
textColor = "#FFFFFF"
font = "sans-serif"

[theme.error]
backgroundColor = "#FF0000"
textColor = "#FFFFFF"
font = "sans-serif"

[theme.success]
backgroundColor = "#32CD32"
textColor = "#FFFFFF"
font = "sans-serif"

[theme.warning]
backgroundColor = "#FFA500"
textColor = "#FFFFFF"
font = "sans-serif"
